### ISSUE TITLE
Research mobile app languages

### ISSUE THREAD

**Issue by AustinGarlick** [AustinGarlick/TimeClockProject#1]

**Comment by AustinGarlick** [comment]
Research

**Comment by AustinGarlick** [comment]
Looks like c# is a fairly common mobile app language. Also javascript. Swift is also good but it is only for IOS.

**Comment by AustinGarlick** [comment]
Maybe Xcode?

**Comment by BrittonJordan** [comment]
Looks like Xcode is free. I would need to run a virtual Mac on my PC if we used Xcode/Swift.

**Comment by AustinGarlick** [comment]
It looks like a great way to create apps for IOS. If we wanted to integrate with android or on pc we would have to do those separately. But I don't think that would be too much of a problem because starting out our code base shouldn't be too complex.

**Comment by AustinGarlick** [comment]
Looks like there is some pretty useful and easy to follow tutorials on lots of swift stuff as well. Maybe look into running a virtual mac on your pc and see how difficult that would be

**Comment by BrittonJordan** [comment]
Yeah this article talks about the similarities between Xcode and Android Studio, and how it isn't difficult to switch between the two. https://buildfire.com/start-android-development-with-an-ios-background/

Ok cool, I'll look into the virtual Mac tomorrow!

**Comment by AustinGarlick** [comment]
ok awesome. Also we should consider if we want to just focus on the backend logic and get something going in like C# first and then later on we can dabble in swift. I'm good with either.

**Comment by BrittonJordan** [comment]
Ok so there are a few free options for running a macOS on my PC, but they are only free for non-commercial use. I did some more research on VS and found this document explaining their usage policy (see attached) Individuals (and small groups < 6 people) are good to use VS Community (free) for commercial use. The U provides us with VS Enterprise, but the app development tool Xamarin is also included in VS Community so I think we would be good. I think doing it in C# would be a good place to at least start if you're good with that!
[VS_Community_2019_ENU.1033.pdf](https://github.com/AustinGarlick/TimeClockProject/files/5691484/VS_Community_2019_ENU.1033.pdf)

**Comment by BrittonJordan** [comment]
I installed VS Community with the Xamarin tool for if we decide to go that route

**Comment by AustinGarlick** [comment]
Lets plan on using VS Community with xamarian then?

**Comment by BrittonJordan** [comment]
Yeah let's do it
